### ISSUE TITLE
randomly sample bitset given fixed number of elements to retain

### ISSUE THREAD

**Issue by slwu89** [mrc-ide/individual#104]
@giovannic for something in safir I realized it would be nice to add a method for `Bitset` objects that would let you randomly sample a `N` number of indices to retain. It can be done somewhat awkwardly right now like this:
```
n <- 100
bset <- Bitset$new(n)$insert(1:n)
num_to_keep <- 30
to_remove <- sample.int(n = n,size = n - num_to_keep,replace = FALSE)
bset$remove(to_remove)
bset$size() == num_to_keep
```
What do you think about making some function that acts on the `IterableBitset` where you tell it `N`, the number of items to retain in the bitset, and then it will randomly sample the indices of the ones to keep? (and accompanying R interface)? I imagine it could be virtually identical to `bitset_sample_internal` except the 2nd argument to `Rcpp::sample` would be `b.size() - N`.
https://github.com/mrc-ide/individual/blob/18ddd6a84a8fc94d7920d71f5cb523764e971df3/inst/include/IterableBitset.h#L436-L464

An important question is what to call this method..."random_subset", "keep", or something else? Also, I just realized this could be accomplished with `filter_bitset`, but the performance benefit of a modifying method might be worth it.

**Comment by slwu89** [comment]
Cool. I'll work something out, especially since it would be useful for safir. For the R6 method, is there a name for this operation you'd like? sample is taken..., subset, keep, random_subset? Open to suggestions (because I don't know what method name clearly communicates to people what this operation is doing).

**Comment by giovannic** [comment]
Ah yes. random_subset seems like the most descriptive name there.
