### ISSUE TITLE
rendering `DoubleVariable` objects

### ISSUE THREAD

**Issue by slwu89** [mrc-ide/individual#122]
We currently don't have a good way to render output from double variable objects. For example, it would be nice if someone could do something like the following:

```
library(individual)
tsteps <- 50
x <- DoubleVariable$new(initial_values = rlnorm(n = 100))

process <- function(timestep) {
  oldx <- x$get_values()
  newx <- oldx + oldx*0.01
  x$queue_update(values = newx)
}

renderer <- Render$new(timesteps = tsteps)

render_process <- function(timestep) {
  renderer$render(name = "my_double_variable",value = x$get_values(),timestep = timestep)
}

simulation_loop(
  variables = list(x=x),
  processes = list(process, render_process),
  timesteps = tsteps
)
```

The design of `Render$.vectors` is for variables with discrete finite states. @giovannic have you worked out any good way to render output for `DoubleVariable` objects in the malaria sim package? I remember that has quite a few float variables, such as the various immunity types.

**Comment by giovannic** [comment]
Ah, yeah. I was thinking we could have different renderers for different shapes of output. [This](https://github.com/mrc-ide/individual/issues/77#issuecomment-799301561) was one I recommended on a different issue.

A double renderer would be cool!

**Comment by slwu89** [comment]
Ok cool! I'll think about what's a good design for it. Unfortunately it doesn't seem like it would make a lot of sense to have a double renderer class inherit from the render class.

**Comment by slwu89** [comment]
Closing this stale issue.
