### ISSUE TITLE
[JOSS] plain LICENSE file not showing OSI conform text

### ISSUE THREAD

**Issue by strengejacke** [mrc-ide/individual#132]
This is related to https://github.com/openjournals/joss-reviews/issues/3539

The plain text file for the LICENSE should contain this text:
https://opensource.org/licenses/MIT

**Comment by giovannic** [comment]
Hello,

Our package is now listed on CRAN which means it must conform to R package conventions. And their best practice is to treat the LICENSE file as a template:

> A name of a license “template” and a file containing specific variables. The most common case is MIT + file LICENSE, where the LICENSE file needs to contain two fields: the year and copyright holder.

- from [their docs](https://r-pkgs.org/license.html)

What do you suggest we do? The full text _does_ appear in LICENSE.md

**Comment by strengejacke** [comment]
Ok, if this is a CRAN requirement and the md-file lists the full text, I think this ok then.
