### ISSUE TITLE
[JOSS] Statement of need

### ISSUE THREAD

**Issue by strengejacke** [mrc-ide/individual#133]
This issue is related to https://github.com/openjournals/joss-reviews/issues/3539.

A statement of need is missing in the software documentation (readme).

**Comment by giovannic** [comment]
Hello,

Our package is now listed on CRAN which means it must conform to R package conventions. And their best practice is to treat the LICENSE file as a template:

> A name of a license “template” and a file containing specific variables. The most common case is MIT + file LICENSE, where the LICENSE file needs to contain two fields: the year and copyright holder.

- from [their docs](https://r-pkgs.org/license.html)

What do you suggest we do? The full text _does_ appear in LICENSE.md

**Comment by strengejacke** [comment]
This issue is not related to the license file.

**Comment by giovannic** [comment]
Sorry, edited in place

**Comment by giovannic** [comment]
Resolved by #137
