### ISSUE TITLE
Bitset removal with indices

### ISSUE THREAD

**Issue by slwu89** [mrc-ide/individual#162]
Currently `Bitset$remove` accepts a vector of elements, not indices to remove. For certain purposes, it would be useful to have another method which accepts either a vector of indices or perhaps a Bitset of indices to flip to zero. This occurs in cases where you have a `Bitset`, say `x` which is used to get values `y` and `z` from `DoubleVariable` objects, and then you only want to keep things in `x` fulfilling some logical condition, like `y > x` (added a use case example in case there's some good obvious solution I missed!)

**Comment by giovannic** [comment]
Sorry, I don't understand how we can remove elements (as opposed to indices) from a bitset? I see bitsets as a set of positive integers, which I have always thought of as indices to individuals. 

If you wanted to combine indices based on logical conditions, couldn't you use $and, $or and $not?

**Comment by slwu89** [comment]
Oh what I mean is something like this:

```
n <- 100

x <- Bitset$new(size = n)$insert(1:n)
x$choose(k = 50)

y <- DoubleVariable$new(initial_values = rexp(n))
z <- DoubleVariable$new(initial_values = rexp(n))

y_vals <- y$get_values(x)
z_vals <- z$get_values(x)

to_remove <- which(y_vals < z_vals)

# after removal of these indices
x$size() - length(to_remove)

# it would be nice to do this
x$remove(to_remove)
```

One way to do it would be to make another bitset equal to the max size of the first, and then AND the first with the appropriate comparison, so we get all those indices which fulfill the comparison and are in the first set.

```
n <- 100

x <- Bitset$new(size = n)$insert(1:n)
xx <- Bitset$new(size = n)
x$choose(k = 50)

y <- DoubleVariable$new(initial_values = rexp(n))
z <- DoubleVariable$new(initial_values = rexp(n))

y_vals <- y$get_values()
z_vals <- z$get_values()
xx$insert(which(y_vals >= z_vals))

x$and(xx)
```

**Comment by giovannic** [comment]
oh I see, wouldn't it make more sense to do double comparisons in the DoubleVariable? Instead of the Bitset? I could imagine something like...

```r
n <- 100

y <- DoubleVariable$new(initial_values = rexp(n))
z <- DoubleVariable$new(initial_values = rexp(n))

# the new functionality here could be that a and b can be vectors (or maybe even variables?), before they were simply scalars
# perhaps a and b could be renamed to gte and lte?
to_remove <- y$get_index_of(b = z$get_values())
```

**Comment by slwu89** [comment]
Yeah that might be a good method in some cases. I think I'll close this issue though, for my specific use case in safir, the 2nd example I posted (making the second bitset `xx`) is sufficient. It comes up when `x` stores something like "has this person been infected or vaccinated before" and `y` and `z` store some values like antibody titres only valid for people in the set given by `x`. Thanks for thinking out loud with me...this was probably not worth an  issue.
