### ISSUE TITLE
You can queue_state_update with an index that is too big

### ISSUE THREAD

**Issue by giovannic** [mrc-ide/individual#35]
Still needs to be specced with a concrete, reduced test case.

But api$queue_state_update should error if you try to update an index that's out of range

**Comment by ceeb950** [comment]
I have been getting an error when the code has run: 
Error in state_apply_updates(state) : 
  vector::_M_range_check: __n (which is 288230376151711743) >= this->size() (which is 157)

and it has not been at all obvious where this is coming from.

**Comment by slwu89** [comment]
fixed https://github.com/mrc-ide/individual/pull/139
