### ISSUE TITLE
Store set of categories in CategoricalVariable

### ISSUE THREAD

**Issue by slwu89** [mrc-ide/individual#74]
I think it might be a good idea to store the set of valid states within `CategoricalVariable`. I have a use case where I'll need multiple categorical variables and having each object know its set of valid states makes rendering output easier. I'm considering writing a rendering prefab to take in an indeterminate number of categorical variables to output counts of each, which would be greatly eased by storing states within the variables (for outputting the marginals or intersections).

**Comment by giovannic** [comment]
This feels quite related to #47 

Is it a duplicate?

Deffo needed

**Comment by slwu89** [comment]
Ah, even more simple, just adding a value to `CategoricalVariable` that stores the unique categories (passed as argument `categories` in the constructor).

**Comment by giovannic** [comment]
Ah ok, but then how do we initialise individuals who have more than one category?

**Comment by slwu89** [comment]
Oh, this isn't touching issue #47. This one would be as simple as adding a line like:
```
self$.categories <- categories
```
to CategoricalVariable$initialize. I just opened an issue for it because I was wanted to make sure this doesn't go against some design philosophy I'm not aware of. It's probably superfluous to have opened an entire issue for such a small change...

**Comment by giovannic** [comment]
Oh I seeeee!

Yes that would be useful.

```r
self$.categories <- categories
```

would not be [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

A `bitset_get_categories` function that gets the categories from the C++ class is the principled way to do it

**Comment by slwu89** [comment]
Cool =] So it _was_ a good idea to check.

Yeah I mostly wanted it so I can do something like this:

```
render_multiple_categorical_variables <- function(renderer, ...) {
  vars <- match.call(expand.dots = FALSE)$`...`
   function(t) {
    for( v in vars) {
       for (c in v$get_categories()) {
          renderer$render(paste0(v,"_",c, '_count'), v$get_size_of(c), t)
       }
    }
  }
}
```
