### ISSUE TITLE
epidemics on networks

### ISSUE THREAD

**Issue by slwu89** [mrc-ide/individual#85]
Long term thoughts, opening here for discussion/keeping a record of wishlist items.

Consider a situation where contact is structured by a network between individuals (different from metapopulation, which can be handled fairly easily by just keeping track of which node each individual is in at any time), an epidemic on a network. To simulate infection, we'd want to find discordant pairs, if we had a bitset for S and a bitset for I individuals, plus some sort of data structure keeping track of edges, we'd want to (in increasing complexity):

1. Simple infection: find for each S the number of I edges (if infection probability is identical for each S-I edge)
2. Heterogeneous infection: find for each S the bitset of I persons (if infection probability depended on some additional attribute of those individuals)

For the simple infection situation, once we have the number of I's connecting to each S, we can just use `multi_probability_bernoulli_process` to sample infections, or sample and schedule a future infection time if infectious contacts don't happen at the points of a Poisson process.

For the heterogeneous infection type, one would need to get, for each S, a subset of a `DoubleVariable` or `IntegerVariable` corresponding to the I's connected to it, which would then be used to sample infection, as the simple infection situation.

Depending on the relative number of S's and I's it may be better to find those I's connected to each S, or those S's connected to each I.

For keeping track of edges a few options are:
1. a bitset for each individual storing their contacts, memory hog. To get discordant pairs just AND this with I (or S).
2. a bitset with  buckets (sparse) for each individual storing their contacts. To get discordant pairs just AND this with I (or S).
3. a sparse matrix, one could check if S > I or S < I and then decide which rows to check to get discordant pairs; that would involve somehow intersecting that row with I (or S).
4. something more [complicated](https://en.wikipedia.org/wiki/Binary_decision_diagram)?

**Comment by giovannic** [comment]
Cool idea!

It would be be worth checking if [network](https://cran.r-project.org/web/packages/network/vignettes/networkVignette.pdf) and [igraph](https://igraph.org/r/) work well in an individual model.

If there's a lot missing, we could implement something.

I'd be interested in 3 for an R implementation. Or an adjacency list for a C++ implementation.

**Comment by pwinskill** [comment]
For future-profing might be worth considering if one of 1-4 works better with multi-level or hierarchical network structures too (classes within schools, hhs within towns or the like)?

**Comment by slwu89** [comment]
Thanks for the feedback @giovannic, I like network because AFAIK [EpiModel](https://www.epimodel.org/) uses it as a base (along with other [statnet](http://statnet.org/) packages), so if it makes sense to use interoperable data structures in "individual" that could potentially increase applicability of the package. I'll be looking into good ways to implement this with sparse matrices in the next month (good ways = being able to work with bitsets).

@pwinskill that's a great point. If the total number of leaves in the hierarchical structure isn't too great I guess using bitsets to represent each individual's membership in each leaf or not would be reasonable. If not, yeah, perhaps something else could be useful. I could see that being useful for the malariamodel, presumably different health services, etc. would be present at each level of hierarchy.

**Comment by slwu89** [comment]
[network](https://cran.r-project.org/package=network) seems like an easy to use solution. Here's a _very rough_ first pass at doing SIR on a bernoulli random graph. I'm sure there are ways to make it more efficient.

[individual_network.pdf](https://github.com/mrc-ide/individual/files/6355476/individual_network.pdf)

**Comment by slwu89** [comment]
Writing notes here after chatting to @giovannic today to keep everything in a central location.

- it's not great that the quick example uses `$.update()` methods directly; what would be ideal would be to make a new class that stores the network, takes in the S and I bitsets and gives the user what they need.
- we want to initially keep putting these enhancements into the "individual" package rather than break them out into another repo; we can always prune complexity later.
- we'd like to use the [network](https://github.com/statnet/network) package for the network data structure. It has a C API for the "network" S3 class that we can use for computation heavy simulations, I opened [an issue](https://github.com/statnet/network/issues/55) to get help on how to interface with that C API from C++ code; thanks to help from one of the authors I have a minimal example of how to use it with Rcpp compiled C++ code [networkRcppExample](https://github.com/slwu89/network/tree/example_rcpp_pkg/inst/examples/networkRcppExample).
- one thing to think about for the future is how to deal with the many different types of networks...I'm initially considering a static network, but we might also have dynamic networks that change independently of the epidemic process, or a dynamic network that changes as a result of the epidemic process. Just something to keep in mind.

**Comment by slwu89** [comment]
Created a class `Network` on branch feat/network to handle static directed or undirected networks https://github.com/slwu89/individual/blob/feat/network/R/network.R

Added following files:

- [src/network_c.h](https://github.com/slwu89/individual/blob/feat/network/src/network_c.h) a C header file for the function that calls "network" package's C API to get the out neighborhood of a vertex (the vertices it is connected to via outbound edges)
- [src/network_c.c](https://github.com/slwu89/individual/blob/feat/network/src/network_c.c) the C function to implement that
- [src/network.cpp](https://github.com/slwu89/individual/blob/feat/network/src/network.cpp) the Cpp file which calls that externally linked C function. The function `network_get_contacts` is called from the `Network` object to get the number of infectious contacts each S person has.
- [R/network.R](https://github.com/slwu89/individual/blob/feat/network/R/network.R) defines the R6 class `Network`
- [tests/testthat/helper-network.R](https://github.com/slwu89/individual/blob/feat/network/tests/testthat/helper-network.R) need to load `library(network)` for the tests
- [tests/testthat/test-network.R](https://github.com/slwu89/individual/blob/feat/network/tests/testthat/test-network.R) a test to make sure it works on a random network

Modified the following files:

- [inst/include/IterableBitset.h](https://github.com/slwu89/individual/blob/feat/network/inst/include/IterableBitset.h#L394) added a public method `exists_safe` to check if a bit is set

**Comment by slwu89** [comment]
Adding notes.

One way to find how many infectious contacts each susceptible has is here; for each infectious person, we find their contacts, then check which ones are susceptible, add to a vector counting infectious contacts. https://github.com/slwu89/individual/blob/feat/network/src/network.cpp#L50 

However, it is potentially easier and cleaner to just add the contacts in `v` to the vector `contacts` directly regardless of the status of contactee and then do bitset and with the bitset of susceptible persons.

**Comment by slwu89** [comment]
Fastest way so far, using `network` API, grab infectious contacts for everyone. Use the bitset of `S` people to to do `contacts$get_values(index = S)`, that gets the infectious contacts for susceptible persons. From there calculate FOI and update normally. 

SIR on a spatial network:
![image](https://user-images.githubusercontent.com/10673535/119915822-2ffa8680-bf18-11eb-93e2-a548f2fe161c.png)

**Comment by slwu89** [comment]
Closing this issue, I've found the best way to run epidemics on networks for another project is make an R package linking to the compiled interface of "individual" and "network" and write a custom infection process.
